### ISSUE TITLE
MKL path in compile.sh

### ISSUE THREAD

**Issue by HaoranDeng** [DoThingYo/Tree-Embedding#1]
Hi, I tried to run sh compile.sh after configuring the environment but it failed, I opened compile.sh and found that the include dir and link dir are located in /opt/intel/oneapi/mkl/2021.3.0/include or /opt/intel/oneapi/ compiler/2021.3.0/linux/compiler/lib/intel64_lin.

Does this mean that IntelMKL has to be installed in the default location and needs to be version 2021.3.0?
I tried changing the paths to the location where I have it installed now, how should I set these paths? 
Thanks in advance:)

**Comment by DoThingYo** [comment]
Sorry for the late reply. You may change the version number to yours and set the path of all MKL files to it at the same time. I have installed mkl several times on different servers with different versions. Change the compilation command to the corresponding version and it will work. Feel free to re-open it if there are further questions.
